### ISSUE TITLE
Discussion of DDT and pyrethroid classes

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/agam-vgsc-report#137]
Edits to discussion sub-section on DDT and pyrethroid classes. Add relevant citations. Add comment on type I versus type II pyrethroids.

- [x] DDT references - CC

- [x] EHH decay difference - AM

- [x] Pyrethroid classes in anopheles - CC

**Comment by cclarkson** [comment]
MJD suggested that the only evidence for type 1/2 pyrethroid differences might be the cockroach/xenopus studies I had found.

With this in mind, and the EHH analysis finished, I will complete this issue and PR now.
