### ISSUE TITLE
PLOS Genetics submission

### ISSUE THREAD

**Issue by cclarkson** [malariagen/agam-vgsc-report#175]
Manuscript needs to be re-formatted for submission to PLOS Genetics

- [x] no footnotes
- [ ] Vancouver style citations
- [x] 200 character title & 70 character short title
- [x] abstract <300 words
- [x] author summary 150-200 words, non-technical summary, first person, accessible, broader context
- [x] references to supplementary must by S1 Table, S1 Figure etc

**Comment by cclarkson** [comment]
will fix Vancouver citations if accepted

**Comment by alimanfoo** [comment]
Just to say, thanks Chris.

>

-- 
If I do not respond to an email within a few days, please feel free to
resend your email and/or contact me by other means.

Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health
Big Data Institute
Li Ka Shing Centre for Health Information and Discovery
Old Road Campus
Headington
Oxford
OX3 7LF
United Kingdom
Phone: +44 (0)1865 743596 or +44 (0)7866 541624
Email: alimanfoo@googlemail.com
Web: http://a <http://purl.org/net/aliman>limanfoo.github.io/
Twitter: @alimanfoo <https://twitter.com/alimanfoo>
