### ISSUE TITLE
hapclust.locate_recombinants

### ISSUE THREAD

**Issue by cclarkson** [malariagen/agam-vgsc-report#45]
Hi @alimanfoo 

Here's the error from when I tried to used locate_recombinants with the largest haplogroup. All other haplogroups worked fine.

IndexError                                Traceback (most recent call last)
<ipython-input-18-2231ca21d734> in <module>()
      1 #remove recombinants - F3 won't build if max-dist is >1 - maybe too complex
----> 2 idx_rec = hapclust.locate_recombinants(cluster_haps, debug=False)
      3 #idx_rec

~/Git/agam-vgsc-report/agam-report-base/src/python/hapclust.py in locate_recombinants(h, debug)
    816 def locate_recombinants(h, debug=False):
    817     """Locate recombinant haplotypes via the four gamete test."""
--> 818     count = count_gametes(np.asarray(h, dtype='i1'))
    819     d = np.all(count > 0, axis=(2, 3))
    820     # indices of recombinant haplotypes - N.B., keep track of different possible solutions

~/Git/agam-vgsc-report/agam-report-base/src/python/hapclust_opt.pyx in hapclust_opt.count_gametes (/home/chris/.pyxbld/temp.linux-x86_64-3.5/pyrex/hapclust_opt.c:2346)()

IndexError: Out of bounds on buffer access (axis 3)

**Comment by alimanfoo** [comment]
This is due to lack of support for multi-allelics. We don't strictly need this for now so closing but can re-open if this becomes an issue.
